"""update celery_task_executions table indexes

Revision ID: 4d91fece40ff
Revises: 0a75002900a1
Create Date: 2026-08-28 18:36:26.931560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d91fece40ff'
down_revision: Union[str, Sequence[str], None] = '0a75002900a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name_args_hash'), table_name='celery_task_executions')
    op.create_index('ix_task_name_celery_task_id', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_celery_task_id', table_name='celery_task_executions')
    op.create_index(op.f('ix_task_name_args_hash'), 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
