services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodb_data:
