services:
  # FastAPI service


  # Nginx service


  # PostgreSQL service (pgvector)
  pgvector:
    image: ankane/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    env_file:
      - ./env/.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgv_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  # Qdrant service (Vector database)


  # Prometheus service (Monitoring for metrics)


  # Grafana service (Visualization for metrics)


  # Node Exporter service (Monitoring for node metrics)


  # Postgres Exporter service (Monitoring for PostgreSQL metrics)