services:
  # FastAPI service


  # Nginx service


  # PostgreSQL service (pgvector)
  pgvector:
    image: ankane/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    env_file:
      - ./env/.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgv_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  # Qdrant service (Vector database)
  qdrant:
    image: qdrant/qdrant:v1.19.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always

  # Prometheus service (Monitoring for metrics)


  # Grafana service (Visualization for metrics)


  # Node Exporter service (Monitoring for node metrics)


  # Postgres Exporter service (Monitoring for PostgreSQL metrics)
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.20.1
    container_name: postgres_exporter
    env_file:
      - ./env/.env.postgres_exporter
    ports:
      - "9187:9187"
    networks:
      - backend
    restart: always
    depends_on:
      - pgvector